In [2]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3])
type(array1), array1.shape

(numpy.ndarray, (3,))

In [3]:
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
type(array2), array2.shape

(numpy.ndarray, (2, 3))

In [4]:
array3 = np.array([[1, 2, 3]])
type(array3), array3.shape

(numpy.ndarray, (1, 3))

In [6]:
# ndim : 차원 확인
array2.ndim

2

In [5]:
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원


In [12]:
list = [1, 2, 3]
type(list)

list

In [13]:
print(type(list))

<class 'list'>


In [16]:
array = np.array(list)
print(type(array))

<class 'numpy.ndarray'>


In [17]:
# dtype 속성 : ndarray 내의 데이터 타입 확인
array.dtype

dtype('int32')

In [ ]:
# ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다

In [20]:
list1 = [1, 2, 'test']
array1 = np.array(list1)
print(array1.dtype)

<U11


In [22]:
list2 = [1, 2, 3.0]
array2 = np.array(list2)
print(array2.dtype)

<U11
float64


In [3]:
# astype() : ndarray 내 데이터값의 타입 변경
# astype()에 인자로 원하는 타입을 문자열로 지정
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [4]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [5]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


In [8]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [9]:
zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [10]:
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [11]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
array2 = array1.reshape(2, 5)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
array3 = array1.reshape(5, 2)
print(array3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# array1.reshape(4, 3)은 변경할 수 없으므로 오류

In [14]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
array2 = array1.reshape(-1, 5)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
array3 = array1.reshape(5, -1)
print(array3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:
# reshape(-1, 1)은 원본 ndarray가 어떤 형태라도 2차원으로 변환
array4 = array1.reshape(-1, 1)
print(array4)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [24]:
array1 = np.arange(8)
print(array1)

[0 1 2 3 4 5 6 7]


In [25]:
array3d = array1.reshape(2, 2, 2)
print(array3d)
print(array3d.tolist())
print(array3d.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
(2, 2, 2)


In [26]:
# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print(array5)
print(array5.tolist())
print(array5.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


In [29]:
# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print(array6)
print(array6.tolist())
print(array6.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


### 인덱싱(Indexing)

In [89]:
import numpy as np

In [31]:
# 1부터 9까지의 1차원 ndarray 생성
array1= np.arange(start=1, stop=10)
print(array1)

[1 2 3 4 5 6 7 8 9]


In [33]:
array1[2], type(array1[2])

(3, numpy.int32)

In [34]:
# 맨 뒤의 값
array1[-1]

9

In [35]:
# 맨 뒤에서 두 번째 값
array1[-2]

8

In [36]:
# 단일 인덱스를 이용해 ndarray 내의 데이터 값도 간단히 수정 가능
array1[0] = 9
array1[8] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [38]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
print(array2d[0, 0])
print(array2d[0, 1])
print(array2d[1, 0])
print(array2d[2, 2])

1
2
4
9


### 슬라이싱

In [ ]:
# 단일 데이터값 추출을 제외하고
# 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입

In [43]:
array1 = np.arange(1, 10)
print(array1)

array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [46]:
array1 = np.arange(1, 10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [54]:
# 2차원 ndarray에서의 슬라이싱도 1차원 ndarray에서의 슬라이싱과 유사
# 단지, 콤마(,)로 로우와 칼럼 인덱스를 지칭하는 부분만 다르다
array2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(array2d)

print(array2d[0:2, 0:2])
print(array2d[1:3, 0:3])
print(array2d[1:3, :])
print(array2d[:, :])
print(array2d[:2, 1:])
print(array2d[:2, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]


In [55]:
array2d[0], array2d[0].shape

(array([1, 2, 3]), (3,))

In [56]:
array2d[1], array2d[1].shape

(array([4, 5, 6]), (3,))

#### 팬시 인덱싱(Fancy Indexing)

In [58]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
array3 = array2d[[0, 1], 2]
print(array3)
print(type(array3))
print(array3.tolist())

[3 6]
<class 'numpy.ndarray'>
[3, 6]


In [61]:
array4 = array2d[[0, 1], 0:2]
print(array4)
print(array4.tolist())

[[1 2]
 [4 5]]
[[1, 2], [4, 5]]


In [63]:
array5 = array2d[[0, 1]]
print(array5)
print(array5.tolist())

[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


#### 불린 인덱싱(Boolean Indexing)

In [65]:
array1d = np.arange(1, 10)
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [66]:
# 넘파이 ndarray 객체에 조건식을 할당하면
array1d > 5

# False, True로 이뤄진 ndarray 객체 반환
# array([False, False, False, False, False,  True,  True,  True,  True])

array([False, False, False, False, False,  True,  True,  True,  True])

In [70]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
boolean_indexes

array([False, False, False, False, False,  True,  True,  True,  True])

In [73]:
# True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장
# 저장된 index 값으로 데이터 조회
array3 = array1d[boolean_indexes]
print(array3)

[6 7 8 9]


In [75]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print(array4)

[6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()

In [ ]:
# 넘파이에서 
# 행렬 정렬 : 
# np.sort() → 넘파이에서 sort() 호출
#            / 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환 
# ndarray.sort() → 행렬 자체에서 sort() 호출
#                 / 원 행렬 자체를 정렬한 형태로 반환, 반환 값은 None 
# 정렬된 행렬의 인덱스 반환 : argsort()

In [78]:
org_array = np.array([3, 1, 9, 5])
print(org_array)

[3 1 9 5]


In [79]:
# np.sort()로 정렬
sort_array1 = np.sort(org_array) 
print(sort_array1)
print(org_array)

[1 3 5 9]
[3 1 9 5]


In [80]:
# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

None
[1 3 5 9]


In [81]:
# 내림차순으로 정렬하기 위해서는 [::-1] 적용
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [82]:
# 행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해
# 로우 방향 또는 칼럼 방향으로 정렬 수행 가능
array2d = np.array([[8, 12],
                    [7, 1]])
print(array2d)

[[ 8 12]
 [ 7  1]]


In [83]:
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print(sort_array2d_axis0)

[[ 7  1]
 [ 8 12]]


In [84]:
sort_array2d_axis1 = np.sort(array2d, axis = 1)
print(sort_array2d_axis1)

[[ 8 12]
 [ 1  7]]


In [85]:
# np.argsort()
# 원본 행렬이 정렬되었을 때
# 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
# 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[1 0 3 2]


In [86]:
# 내림차순으로 정렬 시에 원본 행렬의 인덱스를 구하는 것도
# np.argsort()[::-1]
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)[::-1]
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[2 3 0 1]


In [88]:
# 팬시 인덱스 적용해서 추출
print(org_array[sort_indices])

[9 5 3 1]
