### 행렬 내적과 전치 행렬 구하기

#### 행렬 내적(행렬 곱) : np.dot()

In [2]:
import numpy as np

In [16]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [17]:
# 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 내적 연산 가능
A.shape, B.shape

((2, 3), (3, 2))

In [18]:
dot_product = np.dot(A, B)
# dot_product
print(dot_product)

[[ 58  64]
 [139 154]]


#### 전치 행렬(원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬) : np.transpose()

In [19]:
A = np.array([[1, 2],
             [3, 4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
